---
resolver: lts-10.5
packages:
  - '.'
  - 'dependency'
  - 'shake-ats'
  - 'hs2ats'
extra-deps:
  - dhall-1.9.1
  - shake-ext-2.5.0.0
  - composition-prelude-1.3.0.1
  - language-ats-1.0.0.0
  - cli-setup-0.2.0.1
  - ats-setup-0.3.1.1
  - hspec-dirstream-0.3.0.0
  - dirstream-1.0.3
flags:
  ats-pkg:
    development: false
extra-package-dbs: []
